### ISSUE TITLE
我不知道该如何将日志写到指定文件中，logit的版本是：logit-v0.7.0 

### ISSUE THREAD

**Issue by awei1601** [FishGoddess/logit#14]
![20221221-180511](https://user-images.githubusercontent.com/26304450/208878747-1f8a914e-9c7b-49c0-9ee2-2c196f46c1f2.jpg)

[logit.txt](https://github.com/FishGoddess/logit/files/10276717/logit.txt)
可以将 logit.txt 的后缀改成.go 文件后运行

**Comment by FishGoddess** [comment]
如果要通过 WriterConfig 来指定日志文件的路径，那可以用 Filename 字段，这个字段指定了当前 Writer 的日志文件路径，每个级别也可以单独指定。

不过，用 extension 中的 config 包来初始化 logger 一般是结合配置文件来用的，如果只是程序中初始化 logger 没必要这么复杂，可以参考 [https://github.com/FishGoddess/logit/blob/master/_examples/file.go](https://github.com/FishGoddess/logit/blob/master/_examples/file.go) 中的例子，或者观看我在 B 站上发的一个简单的讲解 [https://www.bilibili.com/video/BV1D44y1d7kp](https://www.bilibili.com/video/BV1D44y1d7kp)。

还有更多的问题欢迎提问 : )
