### ISSUE TITLE
请教一下，怎么按日期滚动生成日志文件？

### ISSUE THREAD

**Issue by creky** [FishGoddess/logit#16]
看了下，貌似有这功能，但翻了一下代码，又没找到这api，只看到了超过最大文件大小了才会滚动。

**Comment by FishGoddess** [comment]
久等~

目前日志文件的拓展只有 [https://github.com/FishGoddess/logit/tree/master/extension/file](https://github.com/FishGoddess/logit/tree/master/extension/file) 这个使用大小和个数进行限制的功能，暂时没有按照日期去滚动的功能哈

如果确实需要按照日期进行滚动，我有以下建议：
1、使用 linux 的 logrotate 机制
2、使用 [https://github.com/lestrrat-go/file-rotatelogs](https://github.com/lestrrat-go/file-rotatelogs) 这个文件库，但这个库目前已经不维护了

其实我也在考虑加入按照日期滚动的功能，或许就会加上，有啥想法也继续提 : )
