### ISSUE TITLE
作者您好，分享我做的一个高性能日志库

### ISSUE THREAD

**Issue by phuslu** [FishGoddess/logit#30]
logit 诞生之处我就注意到了，相比最初的不成熟，如今 logit 各方面已经进步很大了。如果你对超越 zerolog 性能的日志库的实现感兴趣的话，我这个日志也许可以提供一些帮助。

https://github.com/phuslu/log

**Comment by phuslu** [comment]
还有我早期写的中文 README https://github.com/phuslu/log/blob/master/README_zh.md

**Comment by FishGoddess** [comment]
感谢你对 logit 的关注，我看了你写的 README，里面有不少的想法和我当初写 logit 是类似的，包括现在也是 : )
我会抽时间看你的这个日志库代码，希望可以学习到一些东西并给出一些我个人的看法，在此之前，我先点个 star ~

**Comment by phuslu** [comment]
花了一番心思实现 go 1.21 之后引入 slog handler ，目前在各项性能测试中都是明显超过同类。

这是一个详细的第三方测试 https://madkins23.github.io/go-slog/index.html

**Comment by FishGoddess** [comment]
> 花了一番心思实现 go 1.21 之后引入 slog handler ，目前在各项性能测试中都是明显超过同类。
> 
> 这是一个详细的第三方测试 https://madkins23.github.io/go-slog/index.html

点赞~👍
